### ISSUE TITLE
Object.observe adapter

### ISSUE THREAD

**Issue by tomeraz** [mikeric/rivets#408] opened 2014-10-29 06:54 UTC
Can someone write an example of implementing an adapter using object.observe?
10x!

**Comment by slifin** [comment] 2015-03-24 16:44
This is what I've been using but I don't know if it will help you
     rivets.adapters['.'] = {
			observe: function(obj,keypath,callback){
				Object.observe(obj,callback);
			},
			unobserve: function(obj,keypath,callback){
				Object.unobserve(obj,callback);
			},
			get: function(obj,keypath){
				return obj[keypath];
			},
			set: function(obj,keypath,value){
				obj[keypath] = value;
			}
		};

**Comment by slifin** [comment] 2015-03-25 10:04
I think my adapter suffers from this bug: 
https://github.com/mikeric/rivets/issues/83
where you can't set formatters to things

**Comment by Leeds-eBooks** [comment] 2015-08-17 20:57
Closing as not a bug or issue with rivets itself

**Closed by Leeds-eBooks** 2015-08-17 20:57 UTC
