### ISSUE TITLE
formatters dynamic dependencies/arguments or format binders update value?

### ISSUE THREAD

**Issue by andriijas** [mikeric/rivets#293] opened 2014-04-08 11:07 UTC
I have a two way formatter that formats phone numbers into one readable format for presentation, and one sanitized format  that gets set on the model.

However I need the formatter to be more dynamic, i have on the model a value of which country the phone should be formated as but I cant get this value in the formatter because i get only the value in the arguments.

I tried to make a binder out of it which added the whole thing to one single binder without any formatter but i dont findout how to format value for publishing in binders.

Example:  (i dont want US hardcoded here)
```
  rivets.formatters.phone =
    read: (value) ->
      if value? then utils.PhoneFormat(value, 'US') else value
    publish: (value) ->
      if value? then utils.PhoneSanitize(value, 'US') else value
```

**Comment by Leeds-eBooks** [comment] 2015-08-17 20:05
Closing as not sure what the issue is here. @andriijas If you would like this re-opened please say.

**Closed by Leeds-eBooks** 2015-08-17 20:05 UTC
