### ISSUE TITLE
resetting/clearing a model: Uncaught TypeError: cb is not a function

### ISSUE THREAD

**Issue by mkastner** [mikeric/rivets#644] opened 2016-07-22 14:29 UTC
Maybe I am missing something fundamental.

I am trying to clear out error messages from a form, by replacing the the error model with an empty Object.

My model structure looks like this, when the validation fails:

```
models: {
	error: {
		errors: {
			email: {
				message: 'not a valid address',
			},
			password: {
				message: 'is required'
			}
		}
	}
	login: {
		email: '',
		password: ''
	}
}
```

In order to get rid of the error messages after the validation the error object is set to empty {} 

```
models.error = {};

```

But when that happens, this error is being raised:

```
Uncaught TypeError: cb is not a function                        rivets.js:1532
```

Obviously the program expects a function at this point. What's really there is an _undefined_ value.

**Comment by mkastner** [comment] 2016-07-22 15:58
I think, it was connected to this:

[https://github.com/mikeric/rivets/issues/611](https://github.com/mikeric/rivets/issues/611)

**Comment by jccazeaux** [comment] 2016-08-05 16:28
I just had the same problem. I think it's due to [this commit ](https://github.com/mikeric/rivets/commit/e03550bb816d10d32eadab164be07f28e9b6a950)
The code

```javascript
 callback() for callback in callbacks[keypath].slice() when callback in callbacks[keypath]
```
has been replaced with
```javascript
cb() for cb in callbacks[keypath]
```
Some code is missing and causes the error.
@mkastner Could you please reopen the issue
@blikblum Do you remember why you didn't code the `callbacks[keypath].slice() when callback in callbacks[keypath]` ?

**Comment by blikblum** [comment] 2016-08-05 20:43
The only requirement to avoid the mem leak is rename the callback var from callback to cb

The other changes were to remove redundant code:
`when callback in callbacks[keypath]` is redundant and slice is just duplicating the array

Anyway, the fastest way to discover is replace with the old code.

try
`cb() for cb in callbacks[keypath].slice() when cb in callbacks[keypath]`

As a side note a jsfiddle showing the error and tests are desirable

**Comment by jccazeaux** [comment] 2016-08-05 23:30
I don't quite understand this part of code, but it seems necessary to copy the array (with `slice()`) in order to preserve the original size. In some situations the array (out of scope) may change during process. 
[Here is a fiddle to show the error](https://jsfiddle.net/jccazeaux/3Lbjxbxh/)
[The same fiddle with rivets 0.8.1](https://jsfiddle.net/jccazeaux/3Lbjxbxh/3/)

This situation is somehow quite similar to #650 and I'm starting to think it hides a vicious bug in unbind process... but it's just a thought

**Comment by blikblum** [comment] 2016-08-06 00:09
> I don't quite understand this part of code, but it seems necessary to copy the array (with slice()) in order to preserve the original size. In some situations the array (out of scope) may change during process.

I think you  are right.

I suggest changing to 

` cb() for cb in callbacks[keypath].slice() when cb in callbacks[keypath]`

Will fix the mem leak and account for this case.
A test case to avoid future regressions would be good also

**Comment by blikblum** [comment] 2016-08-06 00:45
I reduced the minimum to reproduce the issue: https://jsfiddle.net/3Lbjxbxh/4/

**Comment by blikblum** [comment] 2016-08-06 20:08
I've added a test. You can see here: https://github.com/blikblum/rivets/commit/e80e45b22d44fa23d85ae3e26bbfa2a6503d24aa

**Comment by jccazeaux** [comment] 2016-08-07 17:06
Thanks, it's on the PR.

**Comment by Leeds-eBooks** [comment] 2016-08-08 07:46
PR has been merged.

**Closed by Leeds-eBooks** 2016-08-08 07:46 UTC
