### ISSUE TITLE
"publish-only" option in binders

### ISSUE THREAD

**Issue by aristidesfl** [mikeric/rivets#325] opened 2014-06-19 02:24 UTC
It would be useful if 2-way binders had a way to disable either publishing or dom updating by passing an option when using them in HTML.

Just some ideas:
- `rv-value-publish-only="keypath"`
- `rv-value="keypath" rv-publish-only `
- `rv-value="keypath --publish-only"`

**Comment by Leeds-eBooks** [comment] 2015-08-17 20:48
Closing as it's not a bug, and the supplied workaround is valid. Another (recommended) option would be to supply your own custom one-way binder.

**Closed by Leeds-eBooks** 2015-08-17 20:48 UTC
