### ISSUE TITLE
setter on computed property?

### ISSUE THREAD

**Issue by gutenye** [mikeric/rivets#355] opened 2014-08-24 04:14 UTC
I wan to use a computed property in `<input>`, like `<input rv-value="event.duration < start end">`, getter works fine, but there's no setter. maybe something like:

```javascript
event = {
  duration: function(key, value) {
    if (arguments.length == 2) {
     // this is setter
    return value
  } 

  // this is getter
  return this.start - this.end
 }
}
```

**Comment by Leeds-eBooks** [comment] 2015-08-17 20:53
Closing as not a bug or issue with rivets' documented behaviour

**Closed by Leeds-eBooks** 2015-08-17 20:53 UTC
